{
    'name': 'MRA E-Invoicing Connector',
    'version': '17.0.1.0.0',
    'category': 'Accounting',
    'summary': "MRA E-Invoicing Connector",
    'description': "MRA E-Invoicing Connector",
    'author': 'Rhodes Technologies Ltd',
    'website': "https://www.rhodes.mu",
    'company': 'Rhodes Technologies Ltd, Mauritius',
    'maintainer': 'Rhodes Technologies Ltd',
    'depends': ['account',
                'account_payment',
                'account_debit_note',
                'product'],
    'data': [
        # 'views/res_config_settings_views.xml',
        'data/data.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/company.xml',
        'views/partner.xml',
        'views/invoice_view.xml',
        'views/api_logs_view.xml',
        'views/multi_mra_einvoicing.xml',
        'views/transaction_report.xml',
        'views/invoice_counter.xml',
        'reports/report_invoice.xml',
        'menus/menu.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}